openapi: 3.0.0
info:
  title: Dungeon Generator API
  version: 1.0.0
paths:
  /rooms:
    get:
      summary: Get a list of rooms
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                rooms:
                  - room_id: 1
                    dimensions: [3, 4, 5]
                    sensory_impression: "A dimly lit room with a musty smell."
                    initial_observations: "You see an old wooden table."
                    findings: "You found a rusty key on the table."
                    gm_information: "Secret door hidden behind the table."
                  - room_id: 2
                    dimensions: [6, 6, 6]
                    sensory_impression: "A spacious, well-lit room."
                    initial_observations: "You notice a large mirror."
                    findings: "You found a treasure chest in the corner."
                    gm_information: "Trapdoor under the chest."

    post:
      summary: Create a new room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dimensions:
                  type: array
                  items:
                    type: number
                sensory_impression:
                  type: string
                initial_observations:
                  type: string
                findings:
                  type: string
                gm_information:
                  type: string
      responses:
        '201':
          description: Room created successfully

  /monsters:
    get:
      summary: Get a list of monsters
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                monsters:
                  - monster_id: 1
                    name: "Goblin"
                    description:
                      hp: 20
                      abilities: ["Stealth", "Daggers"]
                  - monster_id: 2
                    name: "Skeleton"
                    description:
                      hp: 30
                      abilities: ["Undead", "Bone Attack"]

    post:
      summary: Create a new monster
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: object
      responses:
        '201':
          description: Monster created successfully